services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb-SGE
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} # <<< ALTERE PARA UMA SENHA SEGURA
      MYSQL_DATABASE: BancoSGE # Nome do banco de dados a ser criado na inicialização
      MYSQL_USER: fatec # Um usuário adicional (não-root) que será criado
      MYSQL_PASSWORD: ${MYSQL_PASSWORD} # Senha para o usuário adicional
    ports:
      - "3308:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
  php:
    build: .
    container_name: php-SGE
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - mariadb
    command: tail -f /dev/null

volumes:
  mariadb_data:
