services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb-SGE
    restart: unless-stopped 
    environment:
      MYSQL_ROOT_PASSWORD: ${GKY59jfiyn}    # <<< ALTERE PARA UMA SENHA SEGURA
      MYSQL_DATABASE: BancoSGE      # Nome do banco de dados a ser criado na inicialização
      MYSQL_USER: fatec                  # Um usuário adicional (não-root) que será criado
      MYSQL_PASSWORD: ${GKY59jfiyn}         # Senha para o usuário adicional
    ports:
      - "3308:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data: